# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GcpLogger < Formula
  desc ""
  homepage "https://github.com/kapetacom/gcp-logger"
  version "0.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kapetacom/gcp-logging/releases/download/v0.0.2/gcp-logging_0.0.2_darwin_amd64.tar.gz"
      sha256 "de28537bc977888ae705358bac78eb5a09005cc5af03b11a8200d79642aeea18"

      def install
        bin.install "gcp-logging"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kapetacom/gcp-logging/releases/download/v0.0.2/gcp-logging_0.0.2_darwin_arm64.tar.gz"
      sha256 "1f0aeafdabcc12d69ff5d66df35af791782e80903206f3eb36856071c8012a2c"

      def install
        bin.install "gcp-logging"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kapetacom/gcp-logging/releases/download/v0.0.2/gcp-logging_0.0.2_linux_arm64.tar.gz"
      sha256 "e84bc6efc9aa890c5783fcab2ee6ad44e56fdb773d37b9edd65aaac80c921c83"

      def install
        bin.install "gcp-logging"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kapetacom/gcp-logging/releases/download/v0.0.2/gcp-logging_0.0.2_linux_amd64.tar.gz"
      sha256 "a655e7436be49deba4fe3e78f537fb6abe23b0f9000be1b09ec896c3b9801cdc"

      def install
        bin.install "gcp-logging"
      end
    end
  end
end
