# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GcpLogger < Formula
  desc ""
  homepage "https://github.com/kapetacom/gcp-logger"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kapetacom/gcp-logging/releases/download/v0.0.1/gcp-logging_0.0.1_darwin_amd64.tar.gz"
      sha256 "beeb52368768d6d91e9ea0cf8094e275b562dd67453fb4c28f2565e98c77bb2a"

      def install
        bin.install "gcp-logging"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kapetacom/gcp-logging/releases/download/v0.0.1/gcp-logging_0.0.1_darwin_arm64.tar.gz"
      sha256 "f552191839272834e65e44cb8ec704dd641dd2ba12e35335568c23289f04bc8b"

      def install
        bin.install "gcp-logging"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kapetacom/gcp-logging/releases/download/v0.0.1/gcp-logging_0.0.1_linux_arm64.tar.gz"
      sha256 "7a49e8bf4ce0c2b6725913f50ab5451efc0b504d1504e52756f87afdfd995ee3"

      def install
        bin.install "gcp-logging"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kapetacom/gcp-logging/releases/download/v0.0.1/gcp-logging_0.0.1_linux_amd64.tar.gz"
      sha256 "25f3c940a4f8dd980894c4c8b6f818e3f62163f2ae3d9f2eea2b6dcd619d796d"

      def install
        bin.install "gcp-logging"
      end
    end
  end
end
