# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KapOpen < Formula
  desc ""
  homepage "https://github.com/kapetacom/kap-open"
  version "0.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kapetacom/kap-open/releases/download/v0.0.2/kap-open_0.0.2_darwin_amd64.tar.gz"
      sha256 "e2e35a0ce2ddfda2e86473e01308cee13ec14b0aec936689d3981201c9bb05fe"

      def install
        bin.install "kap-open"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kapetacom/kap-open/releases/download/v0.0.2/kap-open_0.0.2_darwin_arm64.tar.gz"
      sha256 "77525f1607534a68d05b982adc3d3ad08a2f67fb52f77cab47807b345388ec08"

      def install
        bin.install "kap-open"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/kapetacom/kap-open/releases/download/v0.0.2/kap-open_0.0.2_linux_amd64.tar.gz"
      sha256 "a9375dee2632a71d438484375aea8706beb8ecc0ca568a6c45d33abcb0240807"

      def install
        bin.install "kap-open"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kapetacom/kap-open/releases/download/v0.0.2/kap-open_0.0.2_linux_arm64.tar.gz"
      sha256 "95bb33e7c4ca41297168f26dbafacc51160b5ca034b239e97d7f6a78b0f35bc7"

      def install
        bin.install "kap-open"
      end
    end
  end
end
