# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../custom_download_strategy.rb"
class KapSync < Formula
  desc ""
  homepage "https://github.com/kapetacom/kap-sync"
  version "0.0.6"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kapetacom/kap-sync/releases/download/v0.0.6/kap-sync_0.0.6_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "5c08dc52e24909a87c719ed92c466778491e97377f01fb0bb11fcdd7361e347a"

      def install
        bin.install "kap-sync"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kapetacom/kap-sync/releases/download/v0.0.6/kap-sync_0.0.6_darwin_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "cd0c6544992b7d428a7c14d183545087f614d8bb294a9f63e07f9cd224aefb0b"

      def install
        bin.install "kap-sync"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kapetacom/kap-sync/releases/download/v0.0.6/kap-sync_0.0.6_linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "4a02848bbb35df1b5365d79cfecf2cd8cc160626a8a4680e305ee1b6f68c5c62"

      def install
        bin.install "kap-sync"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kapetacom/kap-sync/releases/download/v0.0.6/kap-sync_0.0.6_linux_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "e62b77afcc970616dd76b217a0bc9c19278c9180b25fa3bf38717a70c4c2ee9b"

      def install
        bin.install "kap-sync"
      end
    end
  end
end
