# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../custom_download_strategy"
class KapSync < Formula
  desc ""
  homepage "https://github.com/kapetacom/kap-sync"
  version "0.0.3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kapetacom/kap-sync/releases/download/v0.0.3/kap-sync_0.0.3_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "f0e5eeee63667c61037c7661e025190f0b0fed775d9e0bd4a34332e7e01b0e83"

      def install
        bin.install "kap-sync"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kapetacom/kap-sync/releases/download/v0.0.3/kap-sync_0.0.3_darwin_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "9b58e6eb0e882edb16c7755b73399268925d31e1c73107f2923481806a9f94e2"

      def install
        bin.install "kap-sync"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kapetacom/kap-sync/releases/download/v0.0.3/kap-sync_0.0.3_linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "090e9e641643416df948b8500186ad2e87e0ac5fd840dacc32e77d17070743ea"

      def install
        bin.install "kap-sync"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kapetacom/kap-sync/releases/download/v0.0.3/kap-sync_0.0.3_linux_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "653ba8e0c82819de1e367b327c840e66416210f9791e91e8bfc735aaf1ec91b9"

      def install
        bin.install "kap-sync"
      end
    end
  end
end
