# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KapOpen < Formula
  desc ""
  homepage "https://github.com/kapetacom/kap-open"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kapetacom/kap-open/releases/download/v0.0.1/kap-open_0.0.1_darwin_amd64.tar.gz"
      sha256 "dfd6b2dcf87ecb8af1f00464905f894c1ac93b17566fe5ff18e64287712b25e2"

      def install
        bin.install "kap-open"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kapetacom/kap-open/releases/download/v0.0.1/kap-open_0.0.1_darwin_arm64.tar.gz"
      sha256 "a557e5d9f6bdfe9866c7734cd54dc95c2082bd1ad30f6301fc0137546841975b"

      def install
        bin.install "kap-open"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kapetacom/kap-open/releases/download/v0.0.1/kap-open_0.0.1_linux_arm64.tar.gz"
      sha256 "38b64db142b4a6d54708c9ac3d5984c1c2225b07ff742968c8b81bc8c9ed206e"

      def install
        bin.install "kap-open"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kapetacom/kap-open/releases/download/v0.0.1/kap-open_0.0.1_linux_amd64.tar.gz"
      sha256 "b6bf059f2752082c89546fdcd804af3c776ae8cce78b80afd55d17bc045e8ee3"

      def install
        bin.install "kap-open"
      end
    end
  end
end
