# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Portpilot < Formula
  desc ""
  homepage "https://github.com/kapetacom/portpilot"
  version "0.0.7"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kapetacom/portpilot/releases/download/v0.0.7/portpilot_0.0.7_darwin_amd64.tar.gz"
      sha256 "5298e55b1124abbb879566acb5797bcfe5a174d43d24b975a97d9a7c965f3ec7"

      def install
        bin.install "portpilot"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kapetacom/portpilot/releases/download/v0.0.7/portpilot_0.0.7_darwin_arm64.tar.gz"
      sha256 "5ef1f98ae3a34af70007593967e2895c29dec2f1fd01d92050cf50dead733064"

      def install
        bin.install "portpilot"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kapetacom/portpilot/releases/download/v0.0.7/portpilot_0.0.7_linux_arm64.tar.gz"
      sha256 "1ce526c9a3fd77a65afedf55f9845fb63f8f4f46f532c08b1cf60a8e31d819a7"

      def install
        bin.install "portpilot"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kapetacom/portpilot/releases/download/v0.0.7/portpilot_0.0.7_linux_amd64.tar.gz"
      sha256 "64b98d51a355be26f84c7e686f121aa40b828b9f457ee658db209aa0c419cc14"

      def install
        bin.install "portpilot"
      end
    end
  end
end
