# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Portpilot < Formula
  desc ""
  homepage "https://github.com/kapetacom/portpilot"
  version "0.0.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kapetacom/portpilot/releases/download/v0.0.2/portpilot_0.0.2_darwin_arm64.tar.gz"
      sha256 "b67a6b7dd1ba3682d0c7e7f61c1683b6b7eb3af5365adce6aa8feaa5fba2fe63"

      def install
        bin.install "portpilot"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kapetacom/portpilot/releases/download/v0.0.2/portpilot_0.0.2_darwin_amd64.tar.gz"
      sha256 "cdcb37abe03635121d92f0c1caa36cb150874d93aa6569660e13fb12dba702ac"

      def install
        bin.install "portpilot"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kapetacom/portpilot/releases/download/v0.0.2/portpilot_0.0.2_linux_arm64.tar.gz"
      sha256 "3b67895c0869ca8f65fa328211fffefa16db848d418b31dadaeb5cfc6cf32b29"

      def install
        bin.install "portpilot"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kapetacom/portpilot/releases/download/v0.0.2/portpilot_0.0.2_linux_amd64.tar.gz"
      sha256 "6deab17eb8579b902c13c39bd02ea64e9ef810be160808be5a89276d4a576ff1"

      def install
        bin.install "portpilot"
      end
    end
  end
end
