# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Portpilot < Formula
  desc ""
  homepage "https://github.com/kapetacom/portpilot"
  version "0.0.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kapetacom/portpilot/releases/download/v0.0.3/portpilot_0.0.3_darwin_amd64.tar.gz"
      sha256 "061a1a76bc50220b1c20f77ac06de660d9e0f4b13800b6807f891f89ef67741b"

      def install
        bin.install "portpilot"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kapetacom/portpilot/releases/download/v0.0.3/portpilot_0.0.3_darwin_arm64.tar.gz"
      sha256 "960aff24227fc0a77cdee9bb1b5c358b45c7c30e926759d7e5895e302a208b15"

      def install
        bin.install "portpilot"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kapetacom/portpilot/releases/download/v0.0.3/portpilot_0.0.3_linux_arm64.tar.gz"
      sha256 "240f09347e016108f8b2763ff2870047888e3b0c6e30b0c3ec3730cdfb202359"

      def install
        bin.install "portpilot"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kapetacom/portpilot/releases/download/v0.0.3/portpilot_0.0.3_linux_amd64.tar.gz"
      sha256 "a7d85c6310af15b42e2d1871ab8c9e04b74f95485cc37aafd25d7a198c729b37"

      def install
        bin.install "portpilot"
      end
    end
  end
end
